all:				App.class LockServer.class Resource.class

App.class:			App.java
				@javac App.java

LockServer.class:		LockServer.java
				@javac LockServer.java

Resource.class:			Resource.java
				@javac Resource.java

clean:
				@rm -rf *.class *~
